language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install -e .[test]
  - pip install coveralls
script: coverage run --source blockhash -m nose -v
after_success:
  - coveralls
